run:
    timeout: 10m
    issues-exit-code: 1
    tests: true

# output:
#     format: colored-line-number

linters:
    enable:
        - gofmt
        - goimports
        - govet
        - errcheck
        - staticcheck
        - ineffassign
        - typecheck
        - unconvert
        - gofumpt

    disable:
        - misspell # Desabilitado por causa de comentários em português

linters-settings:
    govet:
        enable-all: true
        disable:
            - shadow
            - fieldalignment # Desabilitado - otimização desnecessária
    gofmt:
        simplify: true
    goimports:
        local-prefixes: svndiff

issues:
    max-issues-per-linter: 0
    max-same-issues: 0

    exclude-dirs:
        - vendor
        - tmp

    exclude-rules:
        - path: _test\.go
          linters:
              - errcheck
